import RPi.GPIO as gpio
gpio.setwarnings(False)
gpio.setmode(gpio.BCM)
gpio.setup( 2, gpio.IN)
gpio.setup( 3, gpio.IN)
gpio.setup( 4, gpio.IN)
gpio.setup( 5, gpio.IN)
gpio.setup( 6, gpio.IN)
gpio.setup( 7, gpio.IN)
gpio.setup( 8, gpio.IN)
gpio.setup( 9, gpio.IN)
gpio.setup(10, gpio.IN)
gpio.setup(11, gpio.IN)
gpio.setup(12, gpio.IN)
gpio.setup(13, gpio.IN)
gpio.setup(14, gpio.IN)
gpio.setup(15, gpio.IN)
gpio.setup(16, gpio.IN)
gpio.setup(17, gpio.IN)
gpio.setup(18, gpio.IN)
gpio.setup(19, gpio.IN)
gpio.setup(20, gpio.IN)
gpio.setup(21, gpio.IN)
gpio.setup(22, gpio.IN)
gpio.setup(23, gpio.IN)
gpio.setup(24, gpio.IN)
gpio.setup(25, gpio.IN)
gpio.setup(26, gpio.IN)
gpio.setup(27, gpio.IN)

gpio.cleanup()