;CONFIGURACION

;INICIO DE PROGRAMA
	ORG 0X00		;POSICION INICIAL DE MEMORIA
	GOTO START

;CODIGO
START
	BSF	STATUS, 5 	;CAMBIO A BANCO 1, POR DIRECCION
	CLRF	TRISB		;TODOS SON SALIDA
	BCF	STATUS, RP0 	;CAMBIO A BANCO 0, POR NOMBRE
	BCF	STATUS, 5 	;CAMBIO A BANCO 0, POR DIRECCION
	MOVLW	0X00
	MOVWF	PORTB
	GOTO	INC

INC
	ADDLW	0X01
	MOVWF	PORTB
	GOTO	INC
END